language: go
go:
  - tip
install:
  - go get
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: $SLACK_SECURE

