comment:
  layout: header, diff, changes, uncovered
coverage:
  ignore:
  - .*.pb.go
  notify:
    slack:
      default:
        threshold: '0'
        url: https://hooks.slack.com/services/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
status:
    patch: false
    project:
      default:
        branches:
        - master
        target: auto