// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: github.com/piotrkowalczuk/ntypes/ntypes.proto

package ntypes

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bytes represents a byte slice that may be nil.
type Bytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Valid bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Bytes) Reset() {
	*x = Bytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytes) ProtoMessage() {}

func (x *Bytes) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytes.ProtoReflect.Descriptor instead.
func (*Bytes) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{0}
}

func (x *Bytes) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Bytes) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// BytesArray represents an array of byte slices that may be nil.
type BytesArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BytesArray [][]byte `protobuf:"bytes,1,rep,name=bytes_array,json=bytesArray,proto3" json:"bytes_array,omitempty"`
	Valid      bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *BytesArray) Reset() {
	*x = BytesArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesArray) ProtoMessage() {}

func (x *BytesArray) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesArray.ProtoReflect.Descriptor instead.
func (*BytesArray) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{1}
}

func (x *BytesArray) GetBytesArray() [][]byte {
	if x != nil {
		return x.BytesArray
	}
	return nil
}

func (x *BytesArray) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// String represents a string that may be nil.
type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chars string `protobuf:"bytes,1,opt,name=chars,proto3" json:"chars,omitempty"`
	Valid bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{2}
}

func (x *String) GetChars() string {
	if x != nil {
		return x.Chars
	}
	return ""
}

func (x *String) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// StringArray represents an array of strings that may be nil.
type StringArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringArray []string `protobuf:"bytes,1,rep,name=string_array,json=stringArray,proto3" json:"string_array,omitempty"`
	Valid       bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{3}
}

func (x *StringArray) GetStringArray() []string {
	if x != nil {
		return x.StringArray
	}
	return nil
}

func (x *StringArray) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Int32 represents a int32 that may be nil.
type Int32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int32 int32 `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Int32) Reset() {
	*x = Int32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32) ProtoMessage() {}

func (x *Int32) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32.ProtoReflect.Descriptor instead.
func (*Int32) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{4}
}

func (x *Int32) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Int32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Int32Array represents an array of int32s that may be nil.
type Int32Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int32Array []int32 `protobuf:"varint,1,rep,packed,name=int32_array,json=int32Array,proto3" json:"int32_array,omitempty"`
	Valid      bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Int32Array) Reset() {
	*x = Int32Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Array) ProtoMessage() {}

func (x *Int32Array) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Array.ProtoReflect.Descriptor instead.
func (*Int32Array) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{5}
}

func (x *Int32Array) GetInt32Array() []int32 {
	if x != nil {
		return x.Int32Array
	}
	return nil
}

func (x *Int32Array) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Int64 represents a int64 that may be nil.
type Int64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int64 int64 `protobuf:"varint,1,opt,name=int64,proto3" json:"int64,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Int64) Reset() {
	*x = Int64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64) ProtoMessage() {}

func (x *Int64) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64.ProtoReflect.Descriptor instead.
func (*Int64) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{6}
}

func (x *Int64) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Int64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Int64Array represents an array of int64s that may be nil.
type Int64Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int64Array []int64 `protobuf:"varint,1,rep,packed,name=int64_array,json=int64Array,proto3" json:"int64_array,omitempty"`
	Valid      bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Int64Array) Reset() {
	*x = Int64Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Array) ProtoMessage() {}

func (x *Int64Array) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Array.ProtoReflect.Descriptor instead.
func (*Int64Array) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{7}
}

func (x *Int64Array) GetInt64Array() []int64 {
	if x != nil {
		return x.Int64Array
	}
	return nil
}

func (x *Int64Array) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Uint32 represents a Uint32 that may be nil.
type Uint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint32 uint32 `protobuf:"varint,1,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Uint32) Reset() {
	*x = Uint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32) ProtoMessage() {}

func (x *Uint32) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32.ProtoReflect.Descriptor instead.
func (*Uint32) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{8}
}

func (x *Uint32) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Uint32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Uint32Array represents an array of uint32s that may be nil.
type Uint32Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint32Array []uint32 `protobuf:"varint,1,rep,packed,name=uint32_array,json=uint32Array,proto3" json:"uint32_array,omitempty"`
	Valid       bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Uint32Array) Reset() {
	*x = Uint32Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32Array) ProtoMessage() {}

func (x *Uint32Array) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32Array.ProtoReflect.Descriptor instead.
func (*Uint32Array) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{9}
}

func (x *Uint32Array) GetUint32Array() []uint32 {
	if x != nil {
		return x.Uint32Array
	}
	return nil
}

func (x *Uint32Array) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Uint64 represents a Uint64 that may be nil.
type Uint64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint64 uint64 `protobuf:"varint,1,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Uint64) Reset() {
	*x = Uint64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64) ProtoMessage() {}

func (x *Uint64) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64.ProtoReflect.Descriptor instead.
func (*Uint64) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{10}
}

func (x *Uint64) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Uint64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Uint64Array represents an array of uint64s that may be nil.
type Uint64Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint64Array []uint64 `protobuf:"varint,1,rep,packed,name=uint64_array,json=uint64Array,proto3" json:"uint64_array,omitempty"`
	Valid       bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Uint64Array) Reset() {
	*x = Uint64Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64Array) ProtoMessage() {}

func (x *Uint64Array) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64Array.ProtoReflect.Descriptor instead.
func (*Uint64Array) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{11}
}

func (x *Uint64Array) GetUint64Array() []uint64 {
	if x != nil {
		return x.Uint64Array
	}
	return nil
}

func (x *Uint64Array) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Float32 represents a Float32 that may be nil.
type Float32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Float32 float32 `protobuf:"fixed32,1,opt,name=float32,proto3" json:"float32,omitempty"`
	Valid   bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Float32) Reset() {
	*x = Float32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float32) ProtoMessage() {}

func (x *Float32) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float32.ProtoReflect.Descriptor instead.
func (*Float32) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{12}
}

func (x *Float32) GetFloat32() float32 {
	if x != nil {
		return x.Float32
	}
	return 0
}

func (x *Float32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Float32Array represents an array of float32s that may be nil.
type Float32Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Float32Array []float32 `protobuf:"fixed32,1,rep,packed,name=float32_array,json=float32Array,proto3" json:"float32_array,omitempty"`
	Valid        bool      `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Float32Array) Reset() {
	*x = Float32Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float32Array) ProtoMessage() {}

func (x *Float32Array) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float32Array.ProtoReflect.Descriptor instead.
func (*Float32Array) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{13}
}

func (x *Float32Array) GetFloat32Array() []float32 {
	if x != nil {
		return x.Float32Array
	}
	return nil
}

func (x *Float32Array) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Float64 represents a Float64 that may be nil.
type Float64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Float64 float64 `protobuf:"fixed64,1,opt,name=float64,proto3" json:"float64,omitempty"`
	Valid   bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Float64) Reset() {
	*x = Float64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float64) ProtoMessage() {}

func (x *Float64) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float64.ProtoReflect.Descriptor instead.
func (*Float64) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{14}
}

func (x *Float64) GetFloat64() float64 {
	if x != nil {
		return x.Float64
	}
	return 0
}

func (x *Float64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Float64Array represents an array of float64s that may be nil.
type Float64Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Float64Array []float64 `protobuf:"fixed64,1,rep,packed,name=float64_array,json=float64Array,proto3" json:"float64_array,omitempty"`
	Valid        bool      `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Float64Array) Reset() {
	*x = Float64Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float64Array) ProtoMessage() {}

func (x *Float64Array) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float64Array.ProtoReflect.Descriptor instead.
func (*Float64Array) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{15}
}

func (x *Float64Array) GetFloat64Array() []float64 {
	if x != nil {
		return x.Float64Array
	}
	return nil
}

func (x *Float64Array) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// Bool represents a bool that may be nil.
type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bool  bool `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{16}
}

func (x *Bool) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Bool) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// BoolArray represents an array of booleans that may be nil.
type BoolArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoolArray []bool `protobuf:"varint,1,rep,packed,name=bool_array,json=boolArray,proto3" json:"bool_array,omitempty"`
	Valid     bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *BoolArray) Reset() {
	*x = BoolArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolArray) ProtoMessage() {}

func (x *BoolArray) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolArray.ProtoReflect.Descriptor instead.
func (*BoolArray) Descriptor() ([]byte, []int) {
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP(), []int{17}
}

func (x *BoolArray) GetBoolArray() []bool {
	if x != nil {
		return x.BoolArray
	}
	return nil
}

func (x *BoolArray) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_github_com_piotrkowalczuk_ntypes_ntypes_proto protoreflect.FileDescriptor

var file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6f,
	0x74, 0x72, 0x6b, 0x6f, 0x77, 0x61, 0x6c, 0x63, 0x7a, 0x75, 0x6b, 0x2f, 0x6e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0a,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x68, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x72,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22,
	0x33, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x05, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x43,
	0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75,
	0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x0b, 0x55,
	0x69, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x0b, 0x55,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x49,
	0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x07, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x5f,
	0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0c, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22,
	0x30, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x22, 0x40, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x08, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x42, 0x3f, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x70, 0x69, 0x6f, 0x74, 0x72, 0x6b, 0x6f, 0x77, 0x61, 0x6c, 0x63, 0x7a, 0x75, 0x6b,
	0x50, 0x01, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x69, 0x6f, 0x74, 0x72, 0x6b, 0x6f, 0x77, 0x61, 0x6c, 0x63, 0x7a, 0x75, 0x6b, 0x2f, 0x6e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescOnce sync.Once
	file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescData = file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDesc
)

func file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescGZIP() []byte {
	file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescOnce.Do(func() {
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescData)
	})
	return file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDescData
}

var file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_github_com_piotrkowalczuk_ntypes_ntypes_proto_goTypes = []any{
	(*Bytes)(nil),        // 0: ntypes.Bytes
	(*BytesArray)(nil),   // 1: ntypes.BytesArray
	(*String)(nil),       // 2: ntypes.String
	(*StringArray)(nil),  // 3: ntypes.StringArray
	(*Int32)(nil),        // 4: ntypes.Int32
	(*Int32Array)(nil),   // 5: ntypes.Int32Array
	(*Int64)(nil),        // 6: ntypes.Int64
	(*Int64Array)(nil),   // 7: ntypes.Int64Array
	(*Uint32)(nil),       // 8: ntypes.Uint32
	(*Uint32Array)(nil),  // 9: ntypes.Uint32Array
	(*Uint64)(nil),       // 10: ntypes.Uint64
	(*Uint64Array)(nil),  // 11: ntypes.Uint64Array
	(*Float32)(nil),      // 12: ntypes.Float32
	(*Float32Array)(nil), // 13: ntypes.Float32Array
	(*Float64)(nil),      // 14: ntypes.Float64
	(*Float64Array)(nil), // 15: ntypes.Float64Array
	(*Bool)(nil),         // 16: ntypes.Bool
	(*BoolArray)(nil),    // 17: ntypes.BoolArray
}
var file_github_com_piotrkowalczuk_ntypes_ntypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_piotrkowalczuk_ntypes_ntypes_proto_init() }
func file_github_com_piotrkowalczuk_ntypes_ntypes_proto_init() {
	if File_github_com_piotrkowalczuk_ntypes_ntypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Bytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BytesArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StringArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Int32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Int32Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Int64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Int64Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Uint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Uint32Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Uint64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Uint64Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Float32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Float32Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Float64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Float64Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*BoolArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_piotrkowalczuk_ntypes_ntypes_proto_goTypes,
		DependencyIndexes: file_github_com_piotrkowalczuk_ntypes_ntypes_proto_depIdxs,
		MessageInfos:      file_github_com_piotrkowalczuk_ntypes_ntypes_proto_msgTypes,
	}.Build()
	File_github_com_piotrkowalczuk_ntypes_ntypes_proto = out.File
	file_github_com_piotrkowalczuk_ntypes_ntypes_proto_rawDesc = nil
	file_github_com_piotrkowalczuk_ntypes_ntypes_proto_goTypes = nil
	file_github_com_piotrkowalczuk_ntypes_ntypes_proto_depIdxs = nil
}
