// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/piotrkowalczuk/ntypes/ntypes.proto

package ntypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Bytes represents a byte slice that may be nil, set or not set at all.
type Bytes struct {
	Optional             *wrappers.BytesValue `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                 `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{0}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetOptional() *wrappers.BytesValue {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *Bytes) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// BytesArray represents an array of byte slices that may be nil, set or not set at all.
type BytesArray struct {
	Array                [][]byte `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesArray) Reset()         { *m = BytesArray{} }
func (m *BytesArray) String() string { return proto.CompactTextString(m) }
func (*BytesArray) ProtoMessage()    {}
func (*BytesArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{1}
}

func (m *BytesArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesArray.Unmarshal(m, b)
}
func (m *BytesArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesArray.Marshal(b, m, deterministic)
}
func (m *BytesArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesArray.Merge(m, src)
}
func (m *BytesArray) XXX_Size() int {
	return xxx_messageInfo_BytesArray.Size(m)
}
func (m *BytesArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesArray.DiscardUnknown(m)
}

var xxx_messageInfo_BytesArray proto.InternalMessageInfo

func (m *BytesArray) GetArray() [][]byte {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *BytesArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// String represents a string that may be nil, set or not set at all.
type String struct {
	Optional             *wrappers.StringValue `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{2}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetOptional() *wrappers.StringValue {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *String) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// StringArray represents an array of strings that may be nil, set or not set at all.
type StringArray struct {
	Array                []string `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{3}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetArray() []string {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *StringArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int32 represents a int32 that may be nil, set or not set at all.
type Int32 struct {
	Optional             *wrappers.Int32Value `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                 `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Int32) Reset()         { *m = Int32{} }
func (m *Int32) String() string { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()    {}
func (*Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{4}
}

func (m *Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32.Unmarshal(m, b)
}
func (m *Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32.Marshal(b, m, deterministic)
}
func (m *Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32.Merge(m, src)
}
func (m *Int32) XXX_Size() int {
	return xxx_messageInfo_Int32.Size(m)
}
func (m *Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32 proto.InternalMessageInfo

func (m *Int32) GetOptional() *wrappers.Int32Value {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *Int32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int32Array represents an array of int32s that may be nil, set or not set at all.
type Int32Array struct {
	Array                []int32  `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Array) Reset()         { *m = Int32Array{} }
func (m *Int32Array) String() string { return proto.CompactTextString(m) }
func (*Int32Array) ProtoMessage()    {}
func (*Int32Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{5}
}

func (m *Int32Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Array.Unmarshal(m, b)
}
func (m *Int32Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Array.Marshal(b, m, deterministic)
}
func (m *Int32Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Array.Merge(m, src)
}
func (m *Int32Array) XXX_Size() int {
	return xxx_messageInfo_Int32Array.Size(m)
}
func (m *Int32Array) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Array.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Array proto.InternalMessageInfo

func (m *Int32Array) GetArray() []int32 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *Int32Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int64 represents a int64 that may be nil, set or not set at all.
type Int64 struct {
	Optional             *wrappers.Int64Value `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                 `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{6}
}

func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetOptional() *wrappers.Int64Value {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *Int64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int64Array represents an array of int64s that may be nil, set or not set at all.
type Int64Array struct {
	Array                []int64  `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Array) Reset()         { *m = Int64Array{} }
func (m *Int64Array) String() string { return proto.CompactTextString(m) }
func (*Int64Array) ProtoMessage()    {}
func (*Int64Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{7}
}

func (m *Int64Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Array.Unmarshal(m, b)
}
func (m *Int64Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Array.Marshal(b, m, deterministic)
}
func (m *Int64Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Array.Merge(m, src)
}
func (m *Int64Array) XXX_Size() int {
	return xxx_messageInfo_Int64Array.Size(m)
}
func (m *Int64Array) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Array.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Array proto.InternalMessageInfo

func (m *Int64Array) GetArray() []int64 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *Int64Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// UInt32 represents a UInt32 that may be nil, set or not set at all.
type UInt32 struct {
	Optional             *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UInt32) Reset()         { *m = UInt32{} }
func (m *UInt32) String() string { return proto.CompactTextString(m) }
func (*UInt32) ProtoMessage()    {}
func (*UInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{8}
}

func (m *UInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt32.Unmarshal(m, b)
}
func (m *UInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt32.Marshal(b, m, deterministic)
}
func (m *UInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt32.Merge(m, src)
}
func (m *UInt32) XXX_Size() int {
	return xxx_messageInfo_UInt32.Size(m)
}
func (m *UInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt32.DiscardUnknown(m)
}

var xxx_messageInfo_UInt32 proto.InternalMessageInfo

func (m *UInt32) GetOptional() *wrappers.UInt32Value {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *UInt32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// UInt32Array represents an array of uint32s that may be nil, set or not set at all.
type UInt32Array struct {
	Array                []uint32 `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UInt32Array) Reset()         { *m = UInt32Array{} }
func (m *UInt32Array) String() string { return proto.CompactTextString(m) }
func (*UInt32Array) ProtoMessage()    {}
func (*UInt32Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{9}
}

func (m *UInt32Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt32Array.Unmarshal(m, b)
}
func (m *UInt32Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt32Array.Marshal(b, m, deterministic)
}
func (m *UInt32Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt32Array.Merge(m, src)
}
func (m *UInt32Array) XXX_Size() int {
	return xxx_messageInfo_UInt32Array.Size(m)
}
func (m *UInt32Array) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt32Array.DiscardUnknown(m)
}

var xxx_messageInfo_UInt32Array proto.InternalMessageInfo

func (m *UInt32Array) GetArray() []uint32 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *UInt32Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// UInt64 represents a UInt64 that may be nil, set or not set at all.
type UInt64 struct {
	Optional             *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UInt64) Reset()         { *m = UInt64{} }
func (m *UInt64) String() string { return proto.CompactTextString(m) }
func (*UInt64) ProtoMessage()    {}
func (*UInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{10}
}

func (m *UInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt64.Unmarshal(m, b)
}
func (m *UInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt64.Marshal(b, m, deterministic)
}
func (m *UInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt64.Merge(m, src)
}
func (m *UInt64) XXX_Size() int {
	return xxx_messageInfo_UInt64.Size(m)
}
func (m *UInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt64.DiscardUnknown(m)
}

var xxx_messageInfo_UInt64 proto.InternalMessageInfo

func (m *UInt64) GetOptional() *wrappers.UInt64Value {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *UInt64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// UInt64Array represents an array of uint64s that may be nil, set or not set at all.
type UInt64Array struct {
	Array                []uint64 `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UInt64Array) Reset()         { *m = UInt64Array{} }
func (m *UInt64Array) String() string { return proto.CompactTextString(m) }
func (*UInt64Array) ProtoMessage()    {}
func (*UInt64Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{11}
}

func (m *UInt64Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt64Array.Unmarshal(m, b)
}
func (m *UInt64Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt64Array.Marshal(b, m, deterministic)
}
func (m *UInt64Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt64Array.Merge(m, src)
}
func (m *UInt64Array) XXX_Size() int {
	return xxx_messageInfo_UInt64Array.Size(m)
}
func (m *UInt64Array) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt64Array.DiscardUnknown(m)
}

var xxx_messageInfo_UInt64Array proto.InternalMessageInfo

func (m *UInt64Array) GetArray() []uint64 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *UInt64Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Float represents a float that may be nil, set or not set at all.
type Float struct {
	Optional             *wrappers.FloatValue `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                 `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Float) Reset()         { *m = Float{} }
func (m *Float) String() string { return proto.CompactTextString(m) }
func (*Float) ProtoMessage()    {}
func (*Float) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{12}
}

func (m *Float) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Float.Unmarshal(m, b)
}
func (m *Float) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Float.Marshal(b, m, deterministic)
}
func (m *Float) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Float.Merge(m, src)
}
func (m *Float) XXX_Size() int {
	return xxx_messageInfo_Float.Size(m)
}
func (m *Float) XXX_DiscardUnknown() {
	xxx_messageInfo_Float.DiscardUnknown(m)
}

var xxx_messageInfo_Float proto.InternalMessageInfo

func (m *Float) GetOptional() *wrappers.FloatValue {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *Float) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// FloatArray represents an array of floats that may be nil, set or not set at all.
type FloatArray struct {
	Array                []float32 `protobuf:"fixed32,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool      `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FloatArray) Reset()         { *m = FloatArray{} }
func (m *FloatArray) String() string { return proto.CompactTextString(m) }
func (*FloatArray) ProtoMessage()    {}
func (*FloatArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{13}
}

func (m *FloatArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatArray.Unmarshal(m, b)
}
func (m *FloatArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatArray.Marshal(b, m, deterministic)
}
func (m *FloatArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatArray.Merge(m, src)
}
func (m *FloatArray) XXX_Size() int {
	return xxx_messageInfo_FloatArray.Size(m)
}
func (m *FloatArray) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatArray.DiscardUnknown(m)
}

var xxx_messageInfo_FloatArray proto.InternalMessageInfo

func (m *FloatArray) GetArray() []float32 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *FloatArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Double represents a double that that may be nil, set or not set at all.
type Double struct {
	Optional             *wrappers.DoubleValue `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Double) Reset()         { *m = Double{} }
func (m *Double) String() string { return proto.CompactTextString(m) }
func (*Double) ProtoMessage()    {}
func (*Double) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{14}
}

func (m *Double) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Double.Unmarshal(m, b)
}
func (m *Double) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Double.Marshal(b, m, deterministic)
}
func (m *Double) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Double.Merge(m, src)
}
func (m *Double) XXX_Size() int {
	return xxx_messageInfo_Double.Size(m)
}
func (m *Double) XXX_DiscardUnknown() {
	xxx_messageInfo_Double.DiscardUnknown(m)
}

var xxx_messageInfo_Double proto.InternalMessageInfo

func (m *Double) GetOptional() *wrappers.DoubleValue {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *Double) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// DoubleArray represents an array of doubles that may be nil, set or not set at all.
type DoubleArray struct {
	Array                []float64 `protobuf:"fixed64,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool      `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DoubleArray) Reset()         { *m = DoubleArray{} }
func (m *DoubleArray) String() string { return proto.CompactTextString(m) }
func (*DoubleArray) ProtoMessage()    {}
func (*DoubleArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{15}
}

func (m *DoubleArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleArray.Unmarshal(m, b)
}
func (m *DoubleArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleArray.Marshal(b, m, deterministic)
}
func (m *DoubleArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleArray.Merge(m, src)
}
func (m *DoubleArray) XXX_Size() int {
	return xxx_messageInfo_DoubleArray.Size(m)
}
func (m *DoubleArray) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleArray.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleArray proto.InternalMessageInfo

func (m *DoubleArray) GetArray() []float64 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *DoubleArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Bool represents a bool that may be nil, set or not set at all.
type Bool struct {
	Optional             *wrappers.BoolValue `protobuf:"bytes,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Valid                bool                `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{16}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetOptional() *wrappers.BoolValue {
	if m != nil {
		return m.Optional
	}
	return nil
}

func (m *Bool) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// BoolArray represents an array of booleans that may be nil, set or not set at all.
type BoolArray struct {
	Array                []bool   `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolArray) Reset()         { *m = BoolArray{} }
func (m *BoolArray) String() string { return proto.CompactTextString(m) }
func (*BoolArray) ProtoMessage()    {}
func (*BoolArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ab196e8e9f657, []int{17}
}

func (m *BoolArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolArray.Unmarshal(m, b)
}
func (m *BoolArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolArray.Marshal(b, m, deterministic)
}
func (m *BoolArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolArray.Merge(m, src)
}
func (m *BoolArray) XXX_Size() int {
	return xxx_messageInfo_BoolArray.Size(m)
}
func (m *BoolArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolArray.DiscardUnknown(m)
}

var xxx_messageInfo_BoolArray proto.InternalMessageInfo

func (m *BoolArray) GetArray() []bool {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *BoolArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Bytes)(nil), "ntypes.Bytes")
	proto.RegisterType((*BytesArray)(nil), "ntypes.BytesArray")
	proto.RegisterType((*String)(nil), "ntypes.String")
	proto.RegisterType((*StringArray)(nil), "ntypes.StringArray")
	proto.RegisterType((*Int32)(nil), "ntypes.Int32")
	proto.RegisterType((*Int32Array)(nil), "ntypes.Int32Array")
	proto.RegisterType((*Int64)(nil), "ntypes.Int64")
	proto.RegisterType((*Int64Array)(nil), "ntypes.Int64Array")
	proto.RegisterType((*UInt32)(nil), "ntypes.UInt32")
	proto.RegisterType((*UInt32Array)(nil), "ntypes.UInt32Array")
	proto.RegisterType((*UInt64)(nil), "ntypes.UInt64")
	proto.RegisterType((*UInt64Array)(nil), "ntypes.UInt64Array")
	proto.RegisterType((*Float)(nil), "ntypes.Float")
	proto.RegisterType((*FloatArray)(nil), "ntypes.FloatArray")
	proto.RegisterType((*Double)(nil), "ntypes.Double")
	proto.RegisterType((*DoubleArray)(nil), "ntypes.DoubleArray")
	proto.RegisterType((*Bool)(nil), "ntypes.Bool")
	proto.RegisterType((*BoolArray)(nil), "ntypes.BoolArray")
}

func init() {
	proto.RegisterFile("github.com/piotrkowalczuk/ntypes/ntypes.proto", fileDescriptor_170ab196e8e9f657)
}

var fileDescriptor_170ab196e8e9f657 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6b, 0xf2, 0x40,
	0x10, 0x86, 0x89, 0x1a, 0xd1, 0xf5, 0xfb, 0x2e, 0xa1, 0x07, 0x6b, 0x4b, 0x09, 0x9e, 0xbc, 0x34,
	0x01, 0x0d, 0x51, 0x4f, 0xa5, 0x52, 0x0a, 0xbd, 0x15, 0x5b, 0xa5, 0xf4, 0xb6, 0xb1, 0x69, 0x1a,
	0x5c, 0x33, 0x61, 0xdd, 0x54, 0xec, 0xaf, 0x2f, 0xee, 0xa6, 0x85, 0x92, 0x35, 0x19, 0x4f, 0xc9,
	0x2c, 0xcf, 0xc0, 0xc3, 0xfb, 0xc2, 0x90, 0xeb, 0x28, 0x16, 0x1f, 0x59, 0xe0, 0xac, 0x60, 0xe3,
	0xa6, 0x31, 0x08, 0xbe, 0x86, 0x1d, 0x65, 0xab, 0xaf, 0x6c, 0xed, 0x26, 0x62, 0x9f, 0x86, 0xdb,
	0xfc, 0xe3, 0xa4, 0x1c, 0x04, 0x58, 0x4d, 0x35, 0xf5, 0xae, 0x22, 0x80, 0x88, 0x85, 0xae, 0x7c,
	0x0d, 0xb2, 0x77, 0x77, 0xc7, 0x69, 0x9a, 0x86, 0x3c, 0xe7, 0xfa, 0x4b, 0x62, 0xce, 0xf6, 0x22,
	0xdc, 0x5a, 0x63, 0xd2, 0x82, 0x54, 0xc4, 0x90, 0x50, 0xd6, 0x35, 0x6c, 0x63, 0xd0, 0x19, 0x5e,
	0x38, 0x6a, 0xd7, 0xf9, 0xd9, 0x75, 0x24, 0xb9, 0xa4, 0x2c, 0x0b, 0xe7, 0xbf, 0xb0, 0x75, 0x46,
	0xcc, 0x4f, 0xca, 0xe2, 0xb7, 0x6e, 0xcd, 0x36, 0x06, 0xad, 0xb9, 0x1a, 0xfa, 0x13, 0x42, 0x24,
	0x7d, 0xcb, 0x39, 0xdd, 0x1f, 0x18, 0x7a, 0xf8, 0xe9, 0x1a, 0x76, 0x7d, 0xf0, 0x6f, 0xae, 0x86,
	0x23, 0x9b, 0x2f, 0xa4, 0xf9, 0x24, 0x78, 0x9c, 0x44, 0xd6, 0xa4, 0xa0, 0x74, 0x59, 0x50, 0x52,
	0x28, 0xce, 0x69, 0x4a, 0x3a, 0x0a, 0xd7, 0x48, 0xb5, 0xcb, 0xa5, 0x96, 0xc4, 0x7c, 0x48, 0xc4,
	0x68, 0x88, 0x8a, 0x49, 0x92, 0xe8, 0x98, 0x24, 0xad, 0x31, 0x32, 0x31, 0x46, 0xbe, 0x87, 0x35,
	0xf2, 0xbd, 0x53, 0x8c, 0x7c, 0x4f, 0x63, 0x54, 0xaf, 0x2c, 0x6e, 0xa1, 0x42, 0xc2, 0x14, 0xb7,
	0x38, 0x21, 0xa5, 0x29, 0xe9, 0x2c, 0x8e, 0xc5, 0xf4, 0x1f, 0x25, 0xe5, 0x7b, 0x68, 0x29, 0x6c,
	0x50, 0xb9, 0x94, 0x36, 0xa9, 0x46, 0x65, 0x77, 0xf7, 0x0c, 0xa8, 0x40, 0x75, 0x27, 0x49, 0x74,
	0x77, 0x92, 0xd6, 0x18, 0xd5, 0x2a, 0x63, 0xba, 0x83, 0x2c, 0x60, 0x21, 0x2a, 0x26, 0x85, 0xa2,
	0x63, 0x52, 0xb8, 0x46, 0xca, 0x28, 0x97, 0x7a, 0x26, 0x8d, 0x19, 0x00, 0xb3, 0xfc, 0x82, 0x52,
	0xaf, 0x78, 0x9a, 0x00, 0x18, 0x4e, 0x68, 0x4c, 0xda, 0x07, 0x58, 0xa3, 0xd3, 0x2a, 0xd5, 0x99,
	0xdd, 0x90, 0xf3, 0x15, 0x6c, 0x9c, 0xfc, 0x0e, 0xff, 0xbd, 0xc1, 0x8f, 0xc6, 0xab, 0x5d, 0x75,
	0xa0, 0x83, 0xa6, 0xb4, 0x1d, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x2c, 0x59, 0x7c, 0xcb,
	0x05, 0x00, 0x00,
}
