// Code generated by protoc-gen-go.
// source: ntypes.proto
// DO NOT EDIT!

/*
Package ntypes is a generated protocol buffer package.

It is generated from these files:
	ntypes.proto

It has these top-level messages:
	Bytes
	BytesArray
	String
	StringArray
	Int32
	Int32Array
	Int64
	Int64Array
	Uint32
	Uint32Array
	Uint64
	Uint64Array
	Float32
	Float32Array
	Float64
	Float64Array
	Bool
	BoolArray
*/
package ntypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Bytes represents a byte slice that may be nil.
type Bytes struct {
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Valid bool   `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Bytes) Reset()                    { *m = Bytes{} }
func (m *Bytes) String() string            { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()               {}
func (*Bytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bytes) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Bytes) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// BytesArray represents an array of byte slices that may be nil.
type BytesArray struct {
	BytesArray [][]byte `protobuf:"bytes,1,rep,name=bytes_array,json=bytesArray,proto3" json:"bytes_array,omitempty"`
	Valid      bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *BytesArray) Reset()                    { *m = BytesArray{} }
func (m *BytesArray) String() string            { return proto.CompactTextString(m) }
func (*BytesArray) ProtoMessage()               {}
func (*BytesArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BytesArray) GetBytesArray() [][]byte {
	if m != nil {
		return m.BytesArray
	}
	return nil
}

func (m *BytesArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// String represents a string that may be nil.
type String struct {
	Chars string `protobuf:"bytes,1,opt,name=chars" json:"chars,omitempty"`
	Valid bool   `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *String) Reset()                    { *m = String{} }
func (m *String) String() string            { return proto.CompactTextString(m) }
func (*String) ProtoMessage()               {}
func (*String) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *String) GetChars() string {
	if m != nil {
		return m.Chars
	}
	return ""
}

func (m *String) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// StringArray represents an array of strings that may be nil.
type StringArray struct {
	StringArray []string `protobuf:"bytes,1,rep,name=string_array,json=stringArray" json:"string_array,omitempty"`
	Valid       bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *StringArray) Reset()                    { *m = StringArray{} }
func (m *StringArray) String() string            { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()               {}
func (*StringArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StringArray) GetStringArray() []string {
	if m != nil {
		return m.StringArray
	}
	return nil
}

func (m *StringArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int32 represents a int32 that may be nil.
type Int32 struct {
	Int32 int32 `protobuf:"varint,1,opt,name=int32" json:"int32,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Int32) Reset()                    { *m = Int32{} }
func (m *Int32) String() string            { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()               {}
func (*Int32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Int32) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *Int32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int32Array represents an array of int32s that may be nil.
type Int32Array struct {
	Int32Array []int32 `protobuf:"varint,1,rep,packed,name=int32_array,json=int32Array" json:"int32_array,omitempty"`
	Valid      bool    `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Int32Array) Reset()                    { *m = Int32Array{} }
func (m *Int32Array) String() string            { return proto.CompactTextString(m) }
func (*Int32Array) ProtoMessage()               {}
func (*Int32Array) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Int32Array) GetInt32Array() []int32 {
	if m != nil {
		return m.Int32Array
	}
	return nil
}

func (m *Int32Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int64 represents a int64 that may be nil.
type Int64 struct {
	Int64 int64 `protobuf:"varint,1,opt,name=int64" json:"int64,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Int64) Reset()                    { *m = Int64{} }
func (m *Int64) String() string            { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()               {}
func (*Int64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Int64) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Int64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Int64Array represents an array of int64s that may be nil.
type Int64Array struct {
	Int64Array []int64 `protobuf:"varint,1,rep,packed,name=int64_array,json=int64Array" json:"int64_array,omitempty"`
	Valid      bool    `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Int64Array) Reset()                    { *m = Int64Array{} }
func (m *Int64Array) String() string            { return proto.CompactTextString(m) }
func (*Int64Array) ProtoMessage()               {}
func (*Int64Array) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Int64Array) GetInt64Array() []int64 {
	if m != nil {
		return m.Int64Array
	}
	return nil
}

func (m *Int64Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Uint32 represents a Uint32 that may be nil.
type Uint32 struct {
	Uint32 uint32 `protobuf:"varint,1,opt,name=uint32" json:"uint32,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Uint32) Reset()                    { *m = Uint32{} }
func (m *Uint32) String() string            { return proto.CompactTextString(m) }
func (*Uint32) ProtoMessage()               {}
func (*Uint32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Uint32) GetUint32() uint32 {
	if m != nil {
		return m.Uint32
	}
	return 0
}

func (m *Uint32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Uint32Array represents an array of uint32s that may be nil.
type Uint32Array struct {
	Uint32Array []uint32 `protobuf:"varint,1,rep,packed,name=uint32_array,json=uint32Array" json:"uint32_array,omitempty"`
	Valid       bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Uint32Array) Reset()                    { *m = Uint32Array{} }
func (m *Uint32Array) String() string            { return proto.CompactTextString(m) }
func (*Uint32Array) ProtoMessage()               {}
func (*Uint32Array) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Uint32Array) GetUint32Array() []uint32 {
	if m != nil {
		return m.Uint32Array
	}
	return nil
}

func (m *Uint32Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Uint64 represents a Uint64 that may be nil.
type Uint64 struct {
	Uint64 uint64 `protobuf:"varint,1,opt,name=uint64" json:"uint64,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Uint64) Reset()                    { *m = Uint64{} }
func (m *Uint64) String() string            { return proto.CompactTextString(m) }
func (*Uint64) ProtoMessage()               {}
func (*Uint64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Uint64) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

func (m *Uint64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Uint64Array represents an array of uint64s that may be nil.
type Uint64Array struct {
	Uint64Array []uint64 `protobuf:"varint,1,rep,packed,name=uint64_array,json=uint64Array" json:"uint64_array,omitempty"`
	Valid       bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Uint64Array) Reset()                    { *m = Uint64Array{} }
func (m *Uint64Array) String() string            { return proto.CompactTextString(m) }
func (*Uint64Array) ProtoMessage()               {}
func (*Uint64Array) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Uint64Array) GetUint64Array() []uint64 {
	if m != nil {
		return m.Uint64Array
	}
	return nil
}

func (m *Uint64Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Float32 represents a Float32 that may be nil.
type Float32 struct {
	Float32 float32 `protobuf:"fixed32,1,opt,name=float32" json:"float32,omitempty"`
	Valid   bool    `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Float32) Reset()                    { *m = Float32{} }
func (m *Float32) String() string            { return proto.CompactTextString(m) }
func (*Float32) ProtoMessage()               {}
func (*Float32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Float32) GetFloat32() float32 {
	if m != nil {
		return m.Float32
	}
	return 0
}

func (m *Float32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Float32Array represents an array of float32s that may be nil.
type Float32Array struct {
	Float32Array []float32 `protobuf:"fixed32,1,rep,packed,name=float32_array,json=float32Array" json:"float32_array,omitempty"`
	Valid        bool      `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Float32Array) Reset()                    { *m = Float32Array{} }
func (m *Float32Array) String() string            { return proto.CompactTextString(m) }
func (*Float32Array) ProtoMessage()               {}
func (*Float32Array) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Float32Array) GetFloat32Array() []float32 {
	if m != nil {
		return m.Float32Array
	}
	return nil
}

func (m *Float32Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Float64 represents a Float64 that may be nil.
type Float64 struct {
	Float64 float64 `protobuf:"fixed64,1,opt,name=float64" json:"float64,omitempty"`
	Valid   bool    `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Float64) Reset()                    { *m = Float64{} }
func (m *Float64) String() string            { return proto.CompactTextString(m) }
func (*Float64) ProtoMessage()               {}
func (*Float64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Float64) GetFloat64() float64 {
	if m != nil {
		return m.Float64
	}
	return 0
}

func (m *Float64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Float64Array represents an array of float64s that may be nil.
type Float64Array struct {
	Float64Array []float64 `protobuf:"fixed64,1,rep,packed,name=float64_array,json=float64Array" json:"float64_array,omitempty"`
	Valid        bool      `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Float64Array) Reset()                    { *m = Float64Array{} }
func (m *Float64Array) String() string            { return proto.CompactTextString(m) }
func (*Float64Array) ProtoMessage()               {}
func (*Float64Array) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Float64Array) GetFloat64Array() []float64 {
	if m != nil {
		return m.Float64Array
	}
	return nil
}

func (m *Float64Array) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// Bool represents a bool that may be nil.
type Bool struct {
	Bool  bool `protobuf:"varint,1,opt,name=bool" json:"bool,omitempty"`
	Valid bool `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Bool) Reset()                    { *m = Bool{} }
func (m *Bool) String() string            { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()               {}
func (*Bool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Bool) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Bool) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// BoolArray represents an array of booleans that may be nil.
type BoolArray struct {
	BoolArray []bool `protobuf:"varint,1,rep,packed,name=bool_array,json=boolArray" json:"bool_array,omitempty"`
	Valid     bool   `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *BoolArray) Reset()                    { *m = BoolArray{} }
func (m *BoolArray) String() string            { return proto.CompactTextString(m) }
func (*BoolArray) ProtoMessage()               {}
func (*BoolArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *BoolArray) GetBoolArray() []bool {
	if m != nil {
		return m.BoolArray
	}
	return nil
}

func (m *BoolArray) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Bytes)(nil), "ntypes.Bytes")
	proto.RegisterType((*BytesArray)(nil), "ntypes.BytesArray")
	proto.RegisterType((*String)(nil), "ntypes.String")
	proto.RegisterType((*StringArray)(nil), "ntypes.StringArray")
	proto.RegisterType((*Int32)(nil), "ntypes.Int32")
	proto.RegisterType((*Int32Array)(nil), "ntypes.Int32Array")
	proto.RegisterType((*Int64)(nil), "ntypes.Int64")
	proto.RegisterType((*Int64Array)(nil), "ntypes.Int64Array")
	proto.RegisterType((*Uint32)(nil), "ntypes.Uint32")
	proto.RegisterType((*Uint32Array)(nil), "ntypes.Uint32Array")
	proto.RegisterType((*Uint64)(nil), "ntypes.Uint64")
	proto.RegisterType((*Uint64Array)(nil), "ntypes.Uint64Array")
	proto.RegisterType((*Float32)(nil), "ntypes.Float32")
	proto.RegisterType((*Float32Array)(nil), "ntypes.Float32Array")
	proto.RegisterType((*Float64)(nil), "ntypes.Float64")
	proto.RegisterType((*Float64Array)(nil), "ntypes.Float64Array")
	proto.RegisterType((*Bool)(nil), "ntypes.Bool")
	proto.RegisterType((*BoolArray)(nil), "ntypes.BoolArray")
}

func init() { proto.RegisterFile("ntypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcd, 0xaf, 0x9a, 0x40,
	0x14, 0xc5, 0x83, 0x02, 0xca, 0x05, 0x37, 0xa4, 0x69, 0xd8, 0x34, 0x45, 0xbb, 0x71, 0xa5, 0x4d,
	0x21, 0x24, 0xdd, 0xb5, 0x36, 0x31, 0x71, 0x7b, 0x1b, 0x37, 0xdd, 0x34, 0xe0, 0xf3, 0x83, 0xc8,
	0x73, 0x0c, 0x1f, 0xef, 0xc5, 0xf7, 0xd7, 0xbf, 0xcc, 0xdc, 0x41, 0xc7, 0x17, 0xc0, 0xdd, 0x1c,
	0xe6, 0x9c, 0xfb, 0xbb, 0x67, 0x16, 0x80, 0x73, 0x2a, 0x2f, 0xe7, 0x6d, 0x31, 0x3b, 0xe7, 0xac,
	0x64, 0xae, 0x49, 0x6a, 0x12, 0x80, 0xb1, 0xb8, 0x94, 0xdb, 0xc2, 0xfd, 0x04, 0x46, 0xc2, 0x0f,
	0x9e, 0xe6, 0x6b, 0x53, 0x07, 0x49, 0xf0, 0xaf, 0x2f, 0x71, 0x96, 0x3e, 0x79, 0x3d, 0x5f, 0x9b,
	0x0e, 0x91, 0xc4, 0xe4, 0x0f, 0x80, 0x08, 0xfd, 0xce, 0xf3, 0xf8, 0xe2, 0x7e, 0x05, 0x5b, 0x98,
	0xff, 0xc7, 0x5c, 0x7a, 0x9a, 0xdf, 0x9f, 0x3a, 0x08, 0xc9, 0xcd, 0xd0, 0x3c, 0x24, 0x04, 0xf3,
	0x6f, 0x99, 0xa7, 0xa7, 0x3d, 0xbf, 0xdf, 0x1c, 0xe2, 0x9c, 0xd0, 0x16, 0x92, 0x68, 0x49, 0x2d,
	0xc1, 0xa6, 0x14, 0x8d, 0x1e, 0x83, 0x53, 0x08, 0xa9, 0xc0, 0x2d, 0xb4, 0x0b, 0xc5, 0xd2, 0x3c,
	0x27, 0x00, 0x63, 0x75, 0x2a, 0x83, 0x1f, 0xfc, 0x3a, 0xe5, 0x07, 0x01, 0x37, 0x90, 0x44, 0x7b,
	0x6f, 0x11, 0xba, 0xf6, 0x16, 0x66, 0x05, 0x6d, 0x20, 0xa4, 0x37, 0x43, 0x17, 0x39, 0x0a, 0x25,
	0x39, 0x0a, 0x05, 0xb9, 0x8f, 0x24, 0x3a, 0xc9, 0x51, 0xa8, 0x92, 0xa3, 0x50, 0x21, 0xf7, 0x05,
	0xb9, 0x36, 0x34, 0x0f, 0x89, 0xc0, 0x5c, 0x53, 0xbd, 0xcf, 0x60, 0x56, 0xb7, 0xd6, 0x23, 0x94,
	0xaa, 0xfd, 0xcd, 0xd7, 0x4a, 0xad, 0x31, 0x38, 0xd5, 0xc7, 0xe2, 0x23, 0xb4, 0xab, 0x87, 0xcd,
	0x25, 0x3f, 0x0a, 0x6b, 0xbe, 0xec, 0xae, 0xa3, 0x54, 0xdd, 0xfc, 0xba, 0x9c, 0xe4, 0xdf, 0xd5,
	0xd7, 0x89, 0xdf, 0xdd, 0xff, 0x27, 0x0c, 0x96, 0x19, 0x8b, 0x79, 0x51, 0x0f, 0x06, 0x3b, 0x3a,
	0x8a, 0x0d, 0x7a, 0x58, 0xcb, 0x96, 0xe8, 0x0a, 0x1c, 0x19, 0x25, 0xc0, 0x37, 0x18, 0xc9, 0x80,
	0xb2, 0x44, 0x0f, 0x9d, 0x9d, 0x6a, 0xea, 0xde, 0x22, 0x0a, 0xaf, 0x5b, 0xc8, 0x77, 0xd0, 0xb0,
	0x96, 0x0f, 0xb6, 0xa8, 0x6b, 0xd6, 0x5b, 0xdc, 0x3d, 0x85, 0x26, 0xb7, 0xe8, 0x7e, 0x8b, 0xef,
	0xa0, 0x2f, 0x18, 0xcb, 0x5c, 0x17, 0xf4, 0x84, 0xb1, 0x4c, 0xf0, 0x87, 0x28, 0xce, 0x2d, 0x89,
	0x5f, 0x60, 0xf1, 0x04, 0x0d, 0xfd, 0x02, 0xc0, 0xad, 0x0a, 0x76, 0x88, 0x56, 0x72, 0xbd, 0x6e,
	0x9c, 0xb0, 0x98, 0xfc, 0xf3, 0xf7, 0x69, 0x79, 0xa8, 0x92, 0xd9, 0x86, 0x3d, 0xcf, 0xcf, 0x29,
	0x2b, 0xf3, 0x23, 0x7b, 0x8d, 0xb3, 0xcd, 0x5b, 0x75, 0x9c, 0xd3, 0xff, 0x28, 0x31, 0xc5, 0xef,
	0x29, 0x78, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xab, 0xba, 0x21, 0x71, 0xae, 0x04, 0x00, 0x00,
}
